### ISSUE TITLE
Station edit not working

### ISSUE THREAD

**Issue by nlovrens** [karawin/Ka-Radio#77]
Hi,

In 1.9.0 R0 it is not possible to edit stations using web GUI. Also, if all stations are deleted using "Erase all" it is not possible to add stations. Import using txt file is working. Tested with chrome and firefox.

Thank you

**Comment by karawin** [comment]
Yes sorry, a little mistake.
Corrected now.
Update again please.
Thanks

**Comment by nlovrens** [comment]
Hi, yes, edit of the station is working now. There is still an issue if you delete all stations, then it is not possible to add stations with the GUI because list is missing and there is no "Edit" button to push (screenshot attached).

Thanks
![karadio_stations](https://user-images.githubusercontent.com/20867277/54231631-263c0280-4509-11e9-8c7b-e7ea358cd6f1.JPG)

**Comment by karawin** [comment]
Yes again. Thanks.
Ok now
